/* BEGIN EXCLUDE */
/* END EXCLUDE */

class STAcquire : public STNode {
public:
	/* BEGIN SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	STVector3 echo_moment;
	STVector3 moment_per_point;
	STGradientMom *Encode;
	STGradientAmp *ReadoutGradient;
	STReadout *Readout;
	/* END SEQUENCETREE */
	
	STAcquire();
	bool prepare();
	double duration();
};


