/* BEGIN EXCLUDE */
/* END EXCLUDE */

class STArbAcquire : public STNode {
public:
	/* BEGIN SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	STVector3 kspace_offset;
	STGradientMom *Encode;
	STArbGradient *ReadoutGradient;
	STReadout *Readout;
	/* END SEQUENCETREE */
	
	STArbAcquire();
	bool prepare();
	double duration();
};


