/* BEGIN EXCLUDE */
/* END EXCLUDE */

class STCartesianLoop : public STLoop
{
public:
	/* BEGIN SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	STIterator PE1;
	STIterator PE2;
	STVector3 readout_dir;
	STVector3 PE1_dir;
	STVector3 PE2_dir;
	STGradientEchoBlock *Block;
	/* END SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	
	STCartesianLoop();
	bool prepare();
	
	bool loopRun();
};

