/* BEGIN EXCLUDE */
/* END EXCLUDE */

class STCircleGradient : public STArbGradient {
public:
	/* BEGIN SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	STReal kspace_radius_1;
	STReal kspace_radius_2;
	STReal num_cycles;
	STVector3 kspace_direction_1;
	STVector3 kspace_direction_2;
	STVector3 kspace_offset;
	/* END SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	
	STCircleGradient();
	virtual ~STCircleGradient();
	
	virtual Vector3 gradientShape(double t); //t ranges from 0 to 1, accross the plateau, return k-space location
	
	virtual bool prepare();
private:
};

