/* BEGIN EXCLUDE */
/* END EXCLUDE */

class STGradientEchoBlock : public STChain
{
public:
	/* BEGIN SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	STReal TE;
	STReal TR;
	STVector3 kspace_dir;
	STVector3 kspace_echo;
	STReal excite_time;
	STExcite *Excite;
	STAcquire *Acquire;
	STEncode *Rewind;
	/* END SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	
	STGradientEchoBlock();
	bool initialize();
	bool prepare();
};

