/* BEGIN EXCLUDE */
/* END EXCLUDE */

class STGradientMom : public STNode {
public:
	/* BEGIN SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	STVector3 ramp_times_1;
	STVector3 plateau_times;
	STVector3 ramp_times_2;
	STVector3 start_times;
	STVector3 amplitude;
	STInteger alignment;
	STInteger always_min_dur;
	STReal maxamp;
	STReal ramprate;
	/* END SEQUENCETREE -- this section generated by SequenceTree -- do not edit */	
	//events
	STScannerGradient *GX;
	STScannerGradient *GY;
	STScannerGradient *GZ;
	/////////////////////////////////////////////////////
	STGradientMom();
	virtual ~STGradientMom();
	bool initialize();
	bool setMoment(Vector3 mom);
	bool prepare();
	bool run();
	double duration();
	Vector3 terminalMoment();
	Vector3 totalGradientMoment();
	Vector3 gradientStartTimes(); 
	Vector3 gradientEndTimes();
private:
	void delete_events();
};

