/* BEGIN EXCLUDE */
/* END EXCLUDE */

class STGradientAmp : public STNode {
public:
	/* BEGIN SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	STReal ramp_time_1;
	STReal plateau_time;
	STReal ramp_time_2;
	STVector3 amplitude;
	/* END SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	//events
	STScannerGradient *GX;
	STScannerGradient *GY;
	STScannerGradient *GZ;
	/////////////////////////////////////////////////////
	STGradientAmp();
	virtual ~STGradientAmp();
	bool initialize();
	bool prepare();
	bool run();
	double duration();
	Vector3 terminalMoment();
	Vector3 totalGradientMoment();
	Vector3 gradientStartTimes(); 
	Vector3 gradientEndTimes();
private:
	void delete_events();
};

