/* BEGIN EXCLUDE */
/* END EXCLUDE */

class STMultiAcquire : public STNode {
public:
	/* BEGIN SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	STInteger num_echoes;
	STReal echo_spacing;
	STInteger reference_echo;
	STInteger alternating;
	STInteger num_readout_points;
	STReal dwell_time;
	STReal ramp_time;
	STVector3 echo_moment;
	STVector3 moment_per_point;
	STVector3 step_moment;
	STReal maxamp;
	STReal ramprate;
	/* END SEQUENCETREE */
	
	STMultiAcquire();
	bool prepare();
	double duration();
	void setMDHOnline();
private:
	SList<STAcquire *> m_echoes;
};



