/* BEGIN EXCLUDE */
/* END EXCLUDE */

class STRefocus : public STNode {
public:
	/* BEGIN SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	STVector3 gradient_amplitude;
	STReal slice_thickness;
	STReal bandwidth;
	STVector3 crusher_moment;
	STReal flip_angle;
	STGradientMom *Crusher1;
	STGradientAmp *SliceGradient;
	STRF *RF;
	STGradientMom *Crusher2;
	/* END SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	STRefocus();
	bool prepare();
	Vector3 terminalMoment();
	double duration();
};

