/* BEGIN EXCLUDE */
/* END EXCLUDE */

class STRF : public STNode {
public:
	/* BEGIN SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	STReal flip_angle; //degrees
	STReal pulse_duration; //microsec
	STReal reference_fraction; //between 0 and 1
	STReal bandwidth; //Hz
	STReal time_step; //microsec
	STReal phase; //degrees
	STReal frequency; //Hz
	STInteger pulse_type; //1=excitation, 2=refocusing, 0=neither
	STVector3 gradient_amplitude;
	/* END SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	
	//events
	STScannerRFPulse *RF;
	/////////////////////////////////////////////////////
	STRF();
	virtual ~STRF();
	virtual void pulseShape(double cycles,double &re,double &im);
	bool initialize();
	bool prepare();
	bool run();
	double duration();
	double referenceTime();
	Vector3 terminalMoment();
	Vector3 gradientStartTimes(); 
	Vector3 gradientEndTimes();
	void setGradientAmplitude(Vector3 amp);
	double SAR();
	bool shapeChanged() {return m_shape_changed;}
	void setShapeChanged(bool val) {m_shape_changed=val;}
private:
	void delete_events();
	bool m_shape_changed;
};

