/* BEGIN EXCLUDE */
/* END EXCLUDE */ 

class STSincRF : public STRF {
public:
	/* BEGIN SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	STReal num_lobes_left;
	STReal num_lobes_right;
	/* END SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	STSincRF();
	bool prepare();
	void pulseShape(double cycles,double &re,double &im);
};

