/****************************************************************************
** Generated by HaiQ
**
** Project name:  st4controller
** Project date:  Wed Jul 9 2008
** Author: 
****************************************************************************/
#include <QApplication>
#include "stcontrollermainwindow.h"


///////////////////////////////// ** ////////////////////////////////////
int main(int argc, char *argv[])
{
    QApplication app(argc, argv);
    
    STControllerMainWindow W;
    W.showNormal();

    return app.exec();
}

