class STRoot : public STSequence
{
public:
	/* BEGIN SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	/* END SEQUENCETREE -- this section generated by SequenceTree -- do not edit */
	
	STRoot();
	bool prepare();
};
